language: python
python:
  - "3.6"
cache: pip

install:
  - pip install pipenv
  - pipenv install --dev
before_script: flask assets build
script: flask test

sudo: false
notifications:
  email: false
env:
  - FLASK_APP=app.py FLASK_ENV=development

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  skip-cleanup: true
  app:
    master: unconference-tool
    develop: unconference-tool-dev
  on:
    branch: 
      - master
      - develop