"""empty message

Revision ID: 69d509a6ed18
Revises: 
Create Date: 2018-06-14 11:56:26.115539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d509a6ed18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unconferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('tagline', sa.String(length=140), nullable=True),
    sa.Column('twitter_handle', sa.String(length=80), nullable=True),
    sa.Column('hashtag', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=140), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=140), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('other_info', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.Column('given_name', sa.String(length=30), nullable=True),
    sa.Column('family_name', sa.String(length=30), nullable=True),
    sa.Column('twitter_handle', sa.String(length=80), nullable=True),
    sa.Column('job_title', sa.String(length=80), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('mobile_no', sa.String(length=13), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('notes_url', sa.String(length=140), nullable=True),
    sa.Column('unconference_id', sa.Integer(), nullable=False),
    sa.Column('pitched_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitched_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unconference_id'], ['unconferences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unconference_attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('unconference_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unconference_id'], ['unconferences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=140), nullable=False),
    sa.Column('Description', sa.Text(), nullable=False),
    sa.Column('unconference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unconference_id'], ['unconferences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_details', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer_assignemnts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['volunteer_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_assignemnts')
    op.drop_table('session_attendees')
    op.drop_table('volunteer_roles')
    op.drop_table('unconference_attendees')
    op.drop_table('sessions')
    op.drop_table('users')
    op.drop_table('unconferences')
    # ### end Alembic commands ###
