"""empty message

Revision ID: 9b9706aab035
Revises: 69d509a6ed18
Create Date: 2018-07-05 07:03:59.684722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9706aab035'
down_revision = '69d509a6ed18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_session_user_uc', 'session_attendees', ['session_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_session_user_uc', 'session_attendees', type_='unique')
    # ### end Alembic commands ###
